# Hotrod deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hotrod-deployment
  labels:
    app: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - name: hotrod #1st container
        image: jaegertracing/example-hotrod:latest #Dockerhub image
        ports:
        - containerPort: 8080
          name: port1
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector.default.svc:14267"
      - name: hw
        image: karthequian/helloworld:latest
---
kind: Service
apiVersion: v1
metadata:
  name: hotrod-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: hotrod
  ports:
  - name: hotrod-port
    protocol: TCP
    port: 8080