# Wishlist deployment yaml
kind: Secret
apiVersion: v1
metadata:
  name: mysql-connection-secret
data:
  connection-string: c2VydmVyPTEyNy4wLjAuMTt1aWQ9cm9vdDtwd2Q9MTIzNDU7ZGF0YWJhc2U9dGVzdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: mysql-connection-secret
      containers:
      - name: wishlist #1st container
        image: karthequian/wishlist:1.0 #Dockerhub image
        ports:
        - containerPort: 8080 #Exposes the port 8080 of the container
        env:
        - name: PORT #Environment variable key passed to container that is read by application
          value: "8080" # Value of the env port.
      - name: catalog #2nd container
        image: karthequian/wishlist-catalog:1.0
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
      - name: auth #3rd container
        image: karthequian/wishlist-auth:1.0
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/mysql-volume"
        env:
        - name: PORT
          value: "8082"
        - name: MYSQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mysql-connection-secret
              key: connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: wishlist-auth-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8082
    targetPort: 8082