# Wishlist deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
      - name: wishlist #1st container
        image: karthequian/wishlist:1.0 #Dockerhub image
        ports:
        - containerPort: 8080 #Exposes the port 8080 of the container
          name: wishlist-port
        env:
        - name: PORT #Environment variable key passed to container that is read by application
          value: "8080" # Value of the env port.
        livenessProbe:
          httpGet:
            path: /status
            port: 8080 #Name or port number
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: catalog #2nd container
        image: karthequian/wishlist-catalog:1.0
        ports:
        - containerPort: 8081
          name: catalog-port
        env:
        - name: PORT
          value: "8081"
        livenessProbe:
          httpGet:
            path: /status
            port: 8081 #Name or port number
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: auth #3rd container
        image: karthequian/wishlist-auth:1.0
        ports:
        - containerPort: 8082
          name: auth-port
        env:
        - name: PORT
          value: "8082"
        livenessProbe:
          httpGet:
            path: /status
            port: 8082 #Name or port number
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: wishlist-auth-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8082
    targetPort: 8082