# Wishlist deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-app-deployment
  labels:
    app: wishlist-app-deployment
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: wishlist-app-deployment
  template:
    metadata:
      labels:
        app: wishlist-app-deployment
    spec:
      containers:
      - name: wishlist-app-deployment #1st container
        image: karthequian/wishlist:1.0 #Dockerhub image
        ports:
        - containerPort: 8080 #Exposes the port 8080 of the container
        env:
        - name: PORT #Environment variable key passed to container that is read by application
          value: "8080" # Value of the env port.
---
# Wishlist deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog-deployment
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: catalog-deployment
  template:
    metadata:
      labels:
        app: catalog-deployment
    spec:
      containers:
      - name: catalog #2nd container
        image: karthequian/wishlist-catalog:1.0
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
---
# Wishlist deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-auth-deployment
  labels:
    app: wishlist
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: wishlist-auth-deployment
  template:
    metadata:
      labels:
        app: wishlist-auth-deployment
    spec:
      containers:
      - name: auth #3rd container
        image: karthequian/wishlist-auth:1.0
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: wishlist-auth-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8082
    targetPort: 8082