# Default values for wishlist.
# This is a YAML_formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

wishlistImage:
  repository: karthequian/wishlist
  tag: "1.0"
  pullPolicy: IfNotPresent
authImage:
  repository: karthequian/wishlist-auth
  tag: "1.0"
  pullPolicy: IfNotPresent
catalogImage:
  repository: karthequian/wishlist-catalog
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  wishlistPortName: wishlist-port
  wishlistPortValue: 8080
  catalogPortName: catalog-port
  catalogPortValue: 8082
  authPortName: auth-port
  authPortValue: 8081
  port: 80